contact_links:
    - name: ⚛️ Feature Request or Proposal
      about: To submit a feature request or a proposal, follow the RFC process and send a pull request. Do NOT create issues for proposals.
      url: https://github.com/reactjs/rfcs#what-the-process-is
    - name: 📃 Documentation Issue
      url: https://github.com/reactjs/reactjs.org/issues/new
      about: This issue tracker is not for documentation issues. Please file documentation issues here.
    - name: 🤔 Questions and Help
      url: https://reactjs.org/community/support.html
      about: This issue tracker is not for support questions. Please refer to the React community's help and discussion forums.
labels:
    - name: bug
      color: "#d73a4a"
    - name: enhancement
      color: "#a2eeef"
    - name: question
      color: "#d876e3"
    - name: documentation
      color: "#0075ca"
    - name: test
      color: "#c5def5"
    - name: code quality
      color: "#f9d0c4"
milestones:
    - title: v1.0
      description: Initial release
    - title: v2.0
      description: Second major release
    - title: v3.0
      description: Third major release
